<?php

return [
    // ADMIN
    'ad-0' => 'Admin: View Academic Terms',
    'ad-1' => 'Admin: CUD Semester',
    'ad-2' => 'Admin: CUD Medical Year',
    'ad-3' => 'Admin: Record External Grades',
    'ad-4' => 'Admin: CUD Rotation',
    'ad-5' => 'Admin: CUD Classes',
    'ad-6' => 'Admin: Lecturers and Students Allocation to Class',
    'ad-5.1' => 'Admin: Class Assessments Edit & Reset',
    'ad-7' => 'Admin: CUD Role Groups',
    'ad-7.1' => 'Admin: View Role Groups',
    'ad-8' => 'Admin: CUD Sets',
    'ad-8.1' => 'Admin: View Sets',
    'ad-9' => 'Admin: CUD Grading Systems',
    'ad-9.1' => 'Admin: View Grading Systems',
    'ad-10' => 'Admin: CUD Venues',
    'ad-10.1' => 'Admin: View Venues',
    'ad-11' => 'Admin: CUD Departments',
    'ad-11.1' => 'Admin: View Departments',
    'ad-12' => 'Admin: CUD Courses',
    'ad-12.1' => 'Admin: View Courses',
    'ad-13' => 'Admin: CUD User Accounts',
    'ad-13.1' => 'Admin: View User Accounts',
    'ad-14.ad' => 'Admin: CUD Admin Profiles',
    'ad-14.ac' => 'Admin: CUD Academic Profiles',
    'ad-14.s' => 'Admin: CUD Student Profiles',
    'ad-15' => 'Admin: Admin Transcript',
    'ad-16' => 'Admin: Manage Configurations',
    'ad-17' => 'Admin: View Finance',
    'ad-18' => 'Admin: Record Payment',
    'ad-19' => 'Admin: Record Clearance',
    'ad-20' => 'Admin: Cancel Payment',
    'ad-21' => 'Admin: Cancel Clearance',
    'ad-22' => 'Admin: Manage Logs',
    'ad-23' => 'Admin: View Grades',
    'ad-23.1' => 'Admin: Edit Grades',
    'ad-23.2' => 'Admin: Approve Grades',

    // ACADEMIC
    'ac-1' => 'Academic: View Students',
    'ac-2' => 'Academic: CUD Assessments',
    'ac-3' => 'Academic: Add Grades',
    'ac-4' => 'Academic: Administer Students Registration',

    // STUDENTS
    // 's-1' => 'Student: Active',
];
